---
- hosts: localhost
  tasks:
    - name: "Only show diff between test1.txt & test2.txt" 
      copy:
        src: "/tmp/new.txt"
        dest: "/tmp/base.txt"
      check_mode: yes
      diff: yes

