---
- hosts: all
  tasks:
  var_prompt:
    - name: var
      prompt: What var?
      private: no

    - name: Backup IOS
      ios_command:
        commands: show {{ var }}
      register: abc
    - debug: var=abc.stdout_lines
