---
- hosts: all
  tasks:
    - name: Get cksum of my First file
      stat:
        path : "/tmp/base.txt"
      register: myfirstfile

#    - name: Current SHA1
#      set_fact:
#        mf1sha1: "{{ myfirstfile.stat.checksum }}"

    - name: Get cksum of my Second File (If needed you can jump this)
      stat:
        path : "/tmp/new.txt"
      register: mysecondfile

#    - name: Current SHA1
#      set_fact:
#        mf2sha1: "{{ mysecondfile.stat.checksum }}"

    - name: Compilation Changed
      debug:
        msg: "File Compare"
      when:  mysecondfile ==  myfirstfile
      debug:
        msg: "File Different"
      when: mysecondfile !=  myfirstfile

